export const enum ACTIONS {
    CASH_FETCH_WITHDRAW_REQUEST = 'CASH_FETCH_WITHDRAW_REQUEST',
    CASH_FETCH_WITHDRAW_SUCCESS = 'CASH_FETCH_WITHDRAW_SUCCESS',
    CASH_FETCH_WITHDRAW_FAIL = 'CASH_FETCH_WITHDRAW_FAIL'
}